import React from 'react';
export const metadata = {
	title: "Next Hero | Category",
	description: "Generated by create next app for Category",
  };
const page = () => {
	
	return (
		<div>
			category page
		</div>
	);
};

export default page;