import AboutContent from '@/components/AboutContent';
import React from 'react';
export const metadata = {
	title: {
	  default: "Next Hero",
	  template: "%s | Next Hero",
	  keyword: ['about, about, about']
	},
	description: "Generated by create next app",
  };
const About = () => {
	return (
		<div >
			<h1 className='text-center text-3xl underline font-bold my-10'>About Page</h1>
			<AboutContent></AboutContent>

		</div>
	);
};

export default About