import React from 'react';
export const metadata = {
	title: "Next Hero | Login",
	description: "Generated by create next app",
  };
const page = () => {
	return (
		<div>
			login page
		</div>
	);
};

export default page;