import React from 'react';
import style from "./style.module.css"

export const metadata = {
	title: "Next Hero | contact",
	description: "Generated by create next app",
  };
const page = () => {
	
	return (
		<div>
			<h1 className={style.font_lg}>ekhane row css apply kora hoise</h1>
		</div>
	);
};

export default page;