import localFont from "next/font/local";
import "./globals.css";
import Heading from "@/conponents/Heading";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Next Hero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-4`}
      >
        <nav className="flex gap-10 justify-center ">
        <h1>Home</h1>
        <p>|</p>
        <h1>About</h1>
        <p>|</p>
        <h1>Service</h1>
        <p>|</p>
        <h1>Contact</h1>
        
        </nav>
        <Heading></Heading>
        {children}
      </body>
    </html>
  );
}
